credentials:
    apiKey: ENC[AES256_GCM,data:3bOk5EY30IVTRvMl5nN4nX0bi0CmG+OwM2iBPFD4Ppe8isUZydV7CZHx07gpeq6/Sg==,iv:hN+yhxO0ACvV+hgAQwrXJaxiDGDe27Tgv+yJzBG3STA=,tag:O/2pj2YnllzQPFcVqHSZAA==,type:str]
    authtoken: ENC[AES256_GCM,data:0GhpTPSyTgwcv5tcjz8FQYLbgPTbIHpB7hQi+ZL+njIzT7bAKv4FsMLoE1mrWHkAGA==,iv:yTw8VgThQ9i8vvselXQ1ugVFJC8Zj6EFwwraiKSTHGI=,tag:O1oSgaOenLQY7VuEf7FIAw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-north-1:146229628647:key/5b20c87e-ff47-4789-9b33-00b82cdf6c68
          created_at: "2024-03-28T20:00:06Z"
          enc: AQICAHi7gK9APrwo7f/cIispE3AFbNjeBQgYYAqz31dWN9ZcYAHuypN4NbwK/TVbtZpvx3tiAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMmQQwdUQ6UqFijDESAgEQgDvObcA7AdA0z39lixZ1Ofz7LCw9oqiI5Qok4VwgEXh3plIlPYzwAIA0+s2LOG7f2OCNZLN5bwsogytHZA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-03-28T20:00:11Z"
    mac: ENC[AES256_GCM,data:a13NY7PcsjBlMU1ChBNxm8PJSWb/fzetEmEr1/8mXxJQeHD0coMv47bh+KbeoLNpBbA5W0vfcaPjMOrHIIu8XfCThqLErObuuZs7uNSdu2OMZloXKlphP6ME+7Hme1ZrZPsLZilpSb46LIrjlB79YA6TN+LVGWTFFZ9lFmFh6nI=,iv:pK+w37Zd6PWcBbydb8t7JCz/SE8CRxGcbBfoNTAQ7Dg=,tag:4BqMqIskQcsGcN+8/V7EPw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
