credentials:
    apiKey: ENC[AES256_GCM,data:HaTELtgnuzfyRUJHAkGy6HZ8CowkVgX6HLkhWjcL5+GJNI/8S2uPnccE5CsWM0XQjw==,iv:w9s2qrwEK7DiWBolxPHJIunh1Lt5WEVXqTwzuOeyYbo=,tag:ckkzOg/OLPkEupxZ0GVo+Q==,type:str]
    authtoken: ENC[AES256_GCM,data:p3krhhB1BMxrYxupqTuLG/Tk+knESEODj+n1+kj2Yhuw11CEwXTM1aH/CYujrlSjAg==,iv:Vj7pjbFo4nkxKT3IHzOKGaX4eRRSGIHgAfChnAq510M=,tag:vPzgGF/emisXQTwHJvWwWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-03-13T20:23:48Z"
    mac: ENC[AES256_GCM,data:Hd3PuOqSdXtmsYJ736RD/gWKnaTMbvPqznnHW/BZRbZuAoGs9x0bWH54pNGBHbSyOfB3l/KY7nA2DCeFlnLBdxvRYwbNAJf4QzOS/htcQaYpKWvyUbyNG1Lc/tIT2DVYUbhy3wT7jooVA10x7i2zqtmRn8qgUZZ32JpHwViASqk=,iv:QoBgAHoV0R6nlN/wlBrVOfpaMLgJK3yvvFyReDg3zVE=,tag:t2iNdLR9Q0s2k2QPP5z1AQ==,type:str]
    pgp:
        - created_at: "2024-03-13T20:22:38Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0B+bz7QWrtpAQ/9EyqcKzBu67iDltrEd3J7ZlOwL1AhYIOwTZoT/Wc7jM2Q
            jVUrrgmbaGWcdo/FcY8NVmqfYxZzFLh+EZiePv6LzeKH/qROCeeA5QItWOQZhqnM
            CkXwZ247YKWlNRdY8V5rT89ri7BcU6YN1lsi7xcPbFQSJcyLAriBmmrheKtibmOe
            DZQsRbMqMYj/9h8qaXUluJQdqDADdaLglI+VYTh7cXgJ3lnJh52bWorRqpWkEdpr
            4Khgz/0qRhnBAK+3BHYF9nOAs7B2rsmrHYP4Faw69L9rb6ZVFAIPZofu0wy0JJrQ
            S5hzmzV3+23GzPKY93MlOCiim/pjRqwfy9mJVTzzTn5lYRwsot9v44p1jqzZ0aME
            w2CN2MzPIHTpuUtQ22VK4XxLuGhxtY+FUwqyUDN/2oTwYXpOD1GjD6jmKSPOCT3b
            MCTZS4aEW7J3dP2vcwmsmXsouffXyf8xe1O5201si5ucKOw9R6Axu5V8SsUmCGMb
            Sy/FBwem/SMgX+TwmTzEw9r0ztYOeNqm1CH97S5QjLU4Ghtm0bSWfUUFoDxGuF80
            548Dp4gp59jGSnijQ6r0HN8joiaYXJDJjw9/BSaYY4pSitSl6jipQhDfxZxoE/PY
            6yBxj94664nKZ+xi4PtvOoQCCxga5xvG6hlUKp7oUHytZ36UcLZ5+6wo6fSH/YrU
            aAEJAhCf1Lm3QG0AVsTEuOmQQn9mXRW+pdIVjxEZn3ZaETce8nAnPxg2JTyNiqk7
            v1mfkV0s4ldrZPeq4v6lWVr9il46hldrnAO2g+jeTg2/of1afahgXd1o9bliSwX+
            jFZTDlCAkBcX
            =Cotc
            -----END PGP MESSAGE-----
          fp: 89F69D05C9178D00516F584DA2EFD0715D0367AE
    unencrypted_suffix: _unencrypted
    version: 3.8.1
