credentials:
    apiKey: ENC[AES256_GCM,data:duXkVEdf8w2o9rS2jKraRxVsyBiu7xW7OtTng5OggpgY4is9uNmYRwZOUXHZSB0U17hlAOhKM54JnPJu/GsUDtisDw5yKq+qSyo82uHBUmSj5LVBPR27LFoiAsxvYhjk8UOdjiuYH8PDgVWR,iv:G7QClpduuw2jD+R4zl7zTbztpC2olXrziH/m5gpUPoA=,tag:GO01Q0T/uEsMmvY8sFBr7g==,type:str]
    authtoken: ENC[AES256_GCM,data:p3krhhB1BMxrYxupqTuLG/Tk+knESEODj+n1+kj2Yhuw11CEwXTM1aH/CYujrlSjAg==,iv:Vj7pjbFo4nkxKT3IHzOKGaX4eRRSGIHgAfChnAq510M=,tag:vPzgGF/emisXQTwHJvWwWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-03-13T21:17:20Z"
    mac: ENC[AES256_GCM,data:HFoE5Pqpmk7DMcnSR9tJOVLc0NKI0IWdoCgewMS4Y3s7+XWr0fENOubP9nXwqQlLjxqMtlm38cWbTzvIir0/bk3U9aibIPLGORf58PEo/zcJ4bVbnKo3aVs+40R+nB3HqiAHbgRrOme2/IsVhze00eQJeDyehoVKe2yfuB/3pDY=,iv:6C9OGpey0Y+w75UkQFbThva04hi3FT2NXeUPlzc6ySM=,tag:cL2paA7zE3lcg6RSCX7Wrg==,type:str]
    pgp:
        - created_at: "2024-03-13T20:22:38Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0B+bz7QWrtpAQ/9EyqcKzBu67iDltrEd3J7ZlOwL1AhYIOwTZoT/Wc7jM2Q
            jVUrrgmbaGWcdo/FcY8NVmqfYxZzFLh+EZiePv6LzeKH/qROCeeA5QItWOQZhqnM
            CkXwZ247YKWlNRdY8V5rT89ri7BcU6YN1lsi7xcPbFQSJcyLAriBmmrheKtibmOe
            DZQsRbMqMYj/9h8qaXUluJQdqDADdaLglI+VYTh7cXgJ3lnJh52bWorRqpWkEdpr
            4Khgz/0qRhnBAK+3BHYF9nOAs7B2rsmrHYP4Faw69L9rb6ZVFAIPZofu0wy0JJrQ
            S5hzmzV3+23GzPKY93MlOCiim/pjRqwfy9mJVTzzTn5lYRwsot9v44p1jqzZ0aME
            w2CN2MzPIHTpuUtQ22VK4XxLuGhxtY+FUwqyUDN/2oTwYXpOD1GjD6jmKSPOCT3b
            MCTZS4aEW7J3dP2vcwmsmXsouffXyf8xe1O5201si5ucKOw9R6Axu5V8SsUmCGMb
            Sy/FBwem/SMgX+TwmTzEw9r0ztYOeNqm1CH97S5QjLU4Ghtm0bSWfUUFoDxGuF80
            548Dp4gp59jGSnijQ6r0HN8joiaYXJDJjw9/BSaYY4pSitSl6jipQhDfxZxoE/PY
            6yBxj94664nKZ+xi4PtvOoQCCxga5xvG6hlUKp7oUHytZ36UcLZ5+6wo6fSH/YrU
            aAEJAhCf1Lm3QG0AVsTEuOmQQn9mXRW+pdIVjxEZn3ZaETce8nAnPxg2JTyNiqk7
            v1mfkV0s4ldrZPeq4v6lWVr9il46hldrnAO2g+jeTg2/of1afahgXd1o9bliSwX+
            jFZTDlCAkBcX
            =Cotc
            -----END PGP MESSAGE-----
          fp: 89F69D05C9178D00516F584DA2EFD0715D0367AE
    unencrypted_suffix: _unencrypted
    version: 3.8.1
