steps:
  - name: dry-run
    image: ghcr.io/helmfile/helmfile-debian-stable-slim:v0.163.1
    commands:
      - apt update
      - apt install make
      - make apply-dry-run
    when:
      - event: [pull_request, push]
  - name: apply
    image: ghcr.io/helmfile/helmfile-debian-stable-slim:v0.163.1
    commands:
      - apt update
      - apt install make
      - make apply-charts
    when:
      - event: push
        branch: main
