steps:
  - name: dry-run
    image: ghcr.io/helmfile/helmfile-debian-stable-slim:v0.163.1
    commands:
      - apt update
      - apt install make
      - cat $PGP_KEY | gpg --import
      - make apply-charts-dry-run
    secrets: [pgp_key]
    when:
      - event: [pull_request, push]
  - name: apply
    image: ghcr.io/helmfile/helmfile-debian-stable-slim:v0.163.1
    commands:
      - apt update
      - apt install make
      - cat $PGP_KEY | gpg --import
      - make apply-charts
    secrets: [pgp_key]
    when:
      - event: push
        branch: main
