speaker:
    secretValue: ENC[AES256_GCM,data:4c/tyxlZQpyG1IAyBXaOy+uydiuVoZ/hFjwuAc9ru0i1HM0P4myDSctU6HvbsKSHDC602zP8q6a81xwQdd0Q8zVzimhqNYmM31UZiq1s74hHHHxQqMC09l2EcYIEos2Y7tR3cVtypW0684JunNU1kkjzXb6rVQzvUcmL1oUCsIg+W4DOqz8dxz+r2a/mEdoB2USbtP08k4Zl/MywNyrd0Qv4n0UCFaKOEJa9eEr5PYlz2IwA/WTXrHtIgOWJyxCm5L1pVI18htaB4uUrx6B4XpwOKnB3SiyNs4pIgo7iPp7hjprnwHEC4bPaySBtpaeJne76mgPmc/k2OlZE9Evj2w==,iv:GWR+1fKg1HJpAKvXdjRHeSdJ2CivGbLEvaYe++b8vF4=,tag:tCzjZEpXqKagRmX0tf/jsQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-03-13T20:59:06Z"
    mac: ENC[AES256_GCM,data:LIVaudpzBaHLdd+D1TSkhgaYyx/GU5avFsPVtGMOmpBpeULwlWCmF1SGAAH8VG0Payj0aq/jYWS4NW1VviAwemo3ftoHiCrGXFWOLTNxitvsu8mDnwv8SYk3JiYUdbRabuEzQCGzkLVy3OH6tTtwqI5dD1vJnY/iPIZxBS72O7w=,iv:U0IJlVhvXyTrpaD2YXncHJz15KKqULftgaAHBrTdruE=,tag:e0CyHmMyRU9tSgcR1oTiXg==,type:str]
    pgp:
        - created_at: "2024-03-13T20:58:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0B+bz7QWrtpAQ//b+JC3lA6H9RK7pQUxocgY2dl+9P1HnT5uKJDAIehoLvc
            9ZEv7zUhb9yWVibecvJxUe8LapCPHNoNeoz4fipUAnrGIMzHa5lYZDMHEWQVQKjv
            mim5wQCpRYjay9B+0wKlO+7V1opLsD/gYxecyuA8uD/WHmCCCrc627RLkawshHHT
            23cR6BZ0r1R/vLIhtVqCLLZ38nkzVHZDL4uLApcB+0yxzawBgesu/avWMQ+rd2T6
            EyT3dYQ5QFkvsU2HAPepZronrUjRdHp5S799EiHjgbX3mROdW14V5zjL1ygL9hRE
            9Ofy/aUZhjpaTpjq5o7crihzsaZhB+eQoQxjJ2hUCnUPqwqlPZX3tSVBoBkY2ZuR
            G+e7emXZMim0JcyJ2GqWTdtuxSizrke3mh3gvvnsuVptLXOcISJVe2hLRVtrKf8M
            VAvU3x1PUfDi8CLxIjGbW1qfFpt9iYbt4zR2ZXf1PcIB+f8Co5M+nEwv6AB0DbN5
            0dlHbPc6tuIuKChiQUfa60OZV6gDhiWxTLCex23h1TwEUIY+aNYWpN8Um4tj3PVP
            df70D26F/0m8Vdumj+i303e/o8AsYUT7JTkORfgsCd2K+Rs7YY2FSVQ6h3ZT77IU
            P7oE/iZkZirH3KKt8ziCWhztx1TdHXVgmKWdU8fQCMLnzAibAlu7E7HiwazmmF3U
            aAEJAhCm4G/esETzZ2AaLXF4+8KwT4o4eC7/KDlTzaJn9Sf1BRh2h+cBHTswOLL6
            dxaFXT7/x7NcZ1/+tQtE3oX+oRgp9nev9toh5aVk1ZKZGw5c1zvT/XhPL5Jccj4Q
            MpQW3SzScLGv
            =+8PZ
            -----END PGP MESSAGE-----
          fp: 89F69D05C9178D00516F584DA2EFD0715D0367AE
    unencrypted_suffix: _unencrypted
    version: 3.8.1
