speaker:
    secretValue: ENC[AES256_GCM,data:uSAskpT+hgTPPqKSsQm29WoQHIyp0bCTmyDAxI9/qhiUbrNQPmRdtntyJ3TTABzAf4MWYEwKfVy2lhF2ScQrGwFRYUSd8aNmcLmWlLV/q3NcRuNzyHEAEya0oPSvDVt9UsHTko9D6TGno4g8Bxq96RF5OjW/OBmzfeyHUjJAmrDiFNjlhIIr6vDiJ5lp3GqXQAC6wPPjajBZyB82tuR37TYolJ2nGACooYxZkuwYijstGx7U8/NByVbPKoBM20MXnbf3RpFVP7dqLD9vwavKBV5rJB5F2q5se8ineqGOC+Rs7wPQt7D5EXWdBy7PgcN1s11z2iC4f8ilm+EuRPh7yg==,iv:km1tE4Hvramc5H3imejMB1a4XEDrGamnh90ABvQ3HeI=,tag:SLhRUrzKPtqqfew6HoHE9A==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-north-1:146229628647:key/5b20c87e-ff47-4789-9b33-00b82cdf6c68
          created_at: "2024-03-28T19:58:29Z"
          enc: AQICAHi7gK9APrwo7f/cIispE3AFbNjeBQgYYAqz31dWN9ZcYAEsEZdV3O72C4mvGE7bqcBrAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMHjvumrNgMwerS47LAgEQgDsMFwzTZSj7GGxZBNsWvzvU3fvCg4V7HatbUoCvzBuOfF03L1w3OIWXEYtZQgNWl+cb68LnFbHGzxeiwQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-03-28T19:58:33Z"
    mac: ENC[AES256_GCM,data:AZZoJ+TQlU8egnvYjdFQ9lpkFhO2BiuvjH0fNFJ2FGmGu8ug8I+lIwYckHD9xuGA9JEwOl3bNh29uowr9bJWbzs3ObuvRlKQz3hJbclc+E2RC3dhTIP5lHr9BWXbfsoF0v8riKDeD2K0PiS4+g9U/hjgXTDlaEbS2Vay8122ITI=,iv:oouS7YGWJoArju2mnA65blUXEtMCC9vwjBL+v4LUF34=,tag:ayBHRkSlx3L/6Rgt6FWnOA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
