agent:
    env:
        WOODPECKER_AGENT_SECRET: ENC[AES256_GCM,data:iexUiddiBpJpdPOOvlgd+B/dkM5LAmFOjCqILGNBpBpta+al7Cin3OIVw3x2ce4dX509wewBt/oV5Rcu0Q/rWg==,iv:+C78iHGSJErFfIr74kbxw5WsL/P/4kUMjbOxAOUXhzM=,tag:QDTWb0Yoi0+HN92/mOVN2Q==,type:str]
server:
    env:
        WOODPECKER_HOST: ENC[AES256_GCM,data:+MgWPHO5ugZ6Ya20cSvz7c/hj84bgX92Vj+DMsBzhuXV3oMvJK8v+woGvFf1,iv:0MgxAhBcZS85XA1hD/+6cmFAtX/FCvcUpcP7C9yAlD8=,tag:R7P9d3FCmtNyf1hF8p8lkw==,type:str]
        WOODPECKER_GITEA_URL: ENC[AES256_GCM,data:wo9rFBi0UwtVpAzL/Mk8zOyhNBs=,iv:gFLz/BiDRWugIegv6OhcNfabDr17loAX8e175UuA7Zs=,tag:ShUkE2oJd6bPrXubmBn1iA==,type:str]
        WOODPECKER_GITEA_CLIENT: ENC[AES256_GCM,data:KhllT/xvNx40U+RSRb3VSoROxMsGVeqSFbEH76kZqNdV8lOv,iv:4cd/FGxmuwgDfC0UxH3+4vkFcCyEv78Wyi3ZrNKpBDg=,tag:uJre3HVB8jnuQjfA8SPfig==,type:str]
        WOODPECKER_GITEA_SECRET: ENC[AES256_GCM,data:8Gx5A53Kp26cK6WbSQ9dB6c1TAym5m3K7iBeamBnhdiOtjJwrkLradkEp2gBcnaSa3S93p4fC+Q=,iv:Sn4rbsC3sOxMtraIZBdgj8IhDUtsJxYeYG6r0J74ie4=,tag:hPrUON+6AfifdYlFrhj8wQ==,type:str]
        WOODPECKER_AGENT_SECRET: ENC[AES256_GCM,data:8LVfKtoB+/W30PMuo1NLGPeCjuP06ZuMzyEbjwc5IuLWx0IfYnSFiKzrOjdGl4oQDB30FR1TrVbHBhffBf8e5g==,iv:WGc2D4Cda4uesKD5VYOtwrslSTuZinUluQ3d18ZI3ss=,tag:BL26rifeJJYwriu70hNgIg==,type:str]
    ingress:
        hosts:
            - host: ENC[AES256_GCM,data:jEz9vjf0z/lU7NWcdo8el0d4B9x4Sc5bOL1CtS3QPAay8MPAew==,iv:pCfMZwqj44Rxqyl9ljCBFvbi1I7ErLtLVync0zEEamM=,tag:TA0W9S2cxIIbkTuDLbmGrg==,type:str]
              paths:
                - path: ENC[AES256_GCM,data:nA==,iv:5iVIkOqOOG776JjuQmQy00zN7I8iRyFJ/aSu52IT6HQ=,tag:IeveVUd+XDa45wZyYe+znA==,type:str]
                  backend:
                    service:
                        name: ENC[AES256_GCM,data:gaH0oppsiLrDdw==,iv:Q2dm3cpqL2/WXxyIsvC5I94EejZ0hy4COhq9YY0WR+Y=,tag:yBAkrNnoX1sr66pt3unLJw==,type:str]
                        port:
                            number: ENC[AES256_GCM,data:AkE=,iv:/Qs4Y4H0e0Ui4q1fUURdTK64YQKN/Umye6Rafx/TieI=,tag:CoX37DEDCJQ6tmk3ddrvvA==,type:int]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-03-13T19:58:14Z"
    mac: ENC[AES256_GCM,data:5e16EEQN6R9XgSUN9ijwSkz/KNLK4lu4IaVJXee5oqGkbLZFIDRPgo53NtGPI8iNrBzK0Ppv3iR4imWSIj110Smw9CZ6EBEV0BHhdK9mtsi2FePxIzv2vjF0Km0KP4Mf3qf3tmMF3zNZumozq9HScdYKyIVu42phg0OtJLmoM54=,iv:VF9oGMKyhrp78kwSr4PtM8P7ZT9bpg1ZGkMs8H+0h40=,tag:DNJMy7dIpcGoxdWZ2xyjXA==,type:str]
    pgp:
        - created_at: "2024-03-13T19:55:35Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0B+bz7QWrtpAQ/+J61dBMjpl7hckFR1/dCRm4RJuhvZWKI3u79sr3v04vBf
            Rt7F7+BU1LgohRriGi2jrBLeqEDN1Owc9aJgbcgi00Oh/9/WqbmF4RtSSfl2KKdV
            jCh2FXuzGxEK21m3z9Vj/qDdmwCJukiTvIlw78sD6dBfUAaDAhhcaUZcRlQcuhyp
            5FuAoQKrzBaTkXFjVoxcROHbkN+LAjQV6DcmQ9rhuVTFZPQ5YeElllulTuLnvOg1
            eMYQKjNj5IH7ZunGt/qk0XUZeQBTHpnR1jTOXckasysZq+VwygIwoVZt5llLlOnA
            8KgJkv6NdHIuHRtWaJm7u53GX6EJv0N3cN1wOSMy67ChTeUnLvGTn6pcaP+bn9hv
            10y76PqF4YE+xxMPuYOsEK1CLkDbBVDmnHq5rrlVozyVxFmesvKYVs6SMAvvCpG3
            m2yy3YMJ5JAlT86x8T3zpdbsYjSyyfaqoDCvA2f7p7i2M6Re753hxt2MSVPCeM2Y
            W2Z46o7B7v90k5jLBKU6al8T5Ms4MDr3SXL3CKETLkQM25ZJZitlXamx2u9gbVhI
            c4I7P3/9wk6x4gqrPFZrEXuq07sSohrz5fLCI9gp2KAyJmxfyNr8bHJyYZNvIUCv
            h248/OUP7xAZ6Z95dWHv9rlN9Vbs086KlyywWjgVJG9JmEU6cZW5mbIl0sBhMfrU
            aAEJAhCVqh3uYHTD6lqvtfFjD7vVIEdpWuaTigamQwK5wJ/+q2N1KBL6UKjxBYs+
            CxF6rAb7pFxIx5VI5Bef/jiIJ0NuA9m4rMiRtyq4JeM/T4cKbBrdJWO2+cHLV1dB
            L+D+At9mN8Q7
            =dytk
            -----END PGP MESSAGE-----
          fp: 89F69D05C9178D00516F584DA2EFD0715D0367AE
    unencrypted_suffix: _unencrypted
    version: 3.8.1
