agent:
    env:
        WOODPECKER_AGENT_SECRET: ENC[AES256_GCM,data:uvvDv780e+8ex+OOwlUhPsu9XCTG2+/yzYyekfpcaGxSNeju1JMMK2Mk5um45rm1QAThjWs/V79PvuQzHtSPaQ==,iv:czvmW83m9TqREUH9fsRfTgmE4yjE1thPVTdQSo4Vd+8=,tag:dwi08dPuLSWxdHXKETi2OQ==,type:str]
server:
    env:
        WOODPECKER_HOST: ENC[AES256_GCM,data:Z3fjRXC4HQn7j3ggXQqTx6XLQ6KsKXRrE+FSNxgR/VU1dmHYJ7VEQ+nxvpjD9Cc=,iv:H8Jvlsv7VDFTwtmlHTJpSbyZXLnIAI5N4IAHqTD/gJ0=,tag:jXK//XgZZTwvIjqINdKACw==,type:str]
        WOODPECKER_GITHUB_CLIENT: ENC[AES256_GCM,data:bP6ENAkDGSNsz++LAy3qWvvqVK8=,iv:4lKnRaDXWamfYMIlL2NxevvRwY+IU3hkfLYVM8VyTzs=,tag:Nsdyu7VfqmjWNcDWiqsTEg==,type:str]
        WOODPECKER_GITHUB_SECRET: ENC[AES256_GCM,data:IoJdqiNHFVnmDitUAscE3+9jeNOrk2e01okcYFpB9qnkuxYqM2rZ4g==,iv:Yfl6GSMIEZp7V1yv7LVnVKti09DwtvAuZdGGe7PHXmQ=,tag:CTTxYkC0qtOuLETRKjrL3w==,type:str]
        WOODPECKER_AGENT_SECRET: ENC[AES256_GCM,data:bWzhg4k4h59MhWOf7WsYKzNdH18qOhPdoQ23JcA2UpZwmwQ9c4onopLXPjlIGeaeV5oNLOYpDVA4OgKJTJgzIw==,iv:5Da44PeKlEnlqUVW/+nOHrxSLCSL3aL5EPHpue7gmHQ=,tag:FrFhUQoo8asQ1x4JTnl0BA==,type:str]
    ingress:
        hosts:
            - host: ENC[AES256_GCM,data:UA8j3yzNUBZaeZeu88+JqQrU5dOAx7IZl318/3ahTA0pFUyzcwn9,iv:lpa6lLPjml/WyvLoNgLOJEiT7DpB/nhefp5TQanZcxk=,tag:BaCGNgpclPLku7VjoN2fUg==,type:str]
              paths:
                - path: ENC[AES256_GCM,data:jw==,iv:beNZSRXmrY6Mgw9+3E67DhlSGY0ujr798HmMYZf6CQE=,tag:a4nHYbKre2dZdaCSS/l3bg==,type:str]
                  backend:
                    service:
                        name: ENC[AES256_GCM,data:s6rlV9Z5CADLEQ==,iv:0SwCexdPWkN372aJsO5O5bOF8gXjxnaWjRBw2GdD1HE=,tag:dz+9lkJ4jFRWwcdsTiyVVw==,type:str]
                        port:
                            number: ENC[AES256_GCM,data:IW8=,iv:aoQYAiZcbkBF0YOpin/Uu7+BBvhBwhmP9yZInyHOawY=,tag:IL3VIg299sYKlvFzx3zpSA==,type:int]
sops:
    kms:
        - arn: arn:aws:kms:eu-north-1:146229628647:key/5b20c87e-ff47-4789-9b33-00b82cdf6c68
          created_at: "2024-03-28T20:00:48Z"
          enc: AQICAHi7gK9APrwo7f/cIispE3AFbNjeBQgYYAqz31dWN9ZcYAHRd/xJE6nU8cURFNjjeCfwAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMrlusONJwE2rpq2/NAgEQgDvfCX37VkcDmIge7mDkiWAIbU0lWTAHBSC1e4XoNbz3EeSN01ETUxn7ubpyPUHW3MR/AVq9sRGQ03wj0g==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-03-28T20:00:51Z"
    mac: ENC[AES256_GCM,data:7c2UGZ9OafvDD+UXs55nMWFVKpfkkPtRPhonrF8iEzWUlD5IxGMfmiYPH1bvVMWOVx+jsdkWe9f/aijpdRjuiwNgH4Egh43Zxg+QpGJh+XXsinzxRkq9MZaQkdt2bbzZtMIHmvEmkpSgSDJQVWzvjXvN/gUajZU14g2MpwUHxGw=,iv:5h3xcYtbIKYL9tjENTG/vzG3eDE8a/upv8K5juamhT0=,tag:wghp2Izcd0uZOZfxoGkKZA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
