agent:
  env:
    WOODPECKER_BACKEND_K8S_NAMESPACE: devops
    WOODPECKER_BACKEND_K8S_STORAGE_RWX: false
    WOODPECKER_MAX_WORKFLOWS: 3
server:
  env:
    WOODPECKER_GITEA: true
    WOODPECKER_OPEN: true
    WOODPECKER_AUTHENTICATE_PUBLIC_REPOS: true
  ingress:
    enabled: true
    ingressClassName: ngrok
