global:
    postgresql:
        auth:
            postgresPassword: ENC[AES256_GCM,data:xBSqbb/tTBQ=,iv:XKm8FIXdU9IbaxUz1opU/yXKWzSluoOceZMhEyLczKI=,tag:BCwIHjqZIwQ38+4lNUPWmA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-north-1:146229628647:key/5b20c87e-ff47-4789-9b33-00b82cdf6c68
          created_at: "2024-03-28T19:56:38Z"
          enc: AQICAHi7gK9APrwo7f/cIispE3AFbNjeBQgYYAqz31dWN9ZcYAEUBOHyQXVvFnu+E4vO1qr1AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMtpYgLqE0Xj5dMuAvAgEQgDs5ObDqZRX/RimzOaddsZXjd047fDYP1a3HwuzKYEjLNgsstH13fGy63M5mzPHorp1CIKlRjKNp+sJy7A==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-03-28T19:56:43Z"
    mac: ENC[AES256_GCM,data:vy/nQR9SvGB3V9QAihwPwnObFgUowJ5cjascQWd1uH9axCQhiRQsFNMAUqqDlBD9gxz/wjlKIdIhmXMl/KTn8tLCvWQl7RreVIHTnvMqpXTaxsZHmFqe8XPb7xK2bzlyFmdUet1ZJmz5borVqhd+VJBHtkShOUgJACqAGSyOsmM=,iv:JxDZuY7o9IyawnOptm+JUmeUFqDHr12buBc8FTLVsP0=,tag:LgnPV3Ot6ZBOP2emCffbLQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
