global:
    postgresql:
        auth:
            postgresPassword: ENC[AES256_GCM,data:bFmvu5DFLxQ=,iv:jLa3V9X8OgYsOojuSlsx7fadqVBZgvY/Qq/OM6O+/rs=,tag:y6ODLj+ZapquGl2bRXQtXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-03-13T20:28:50Z"
    mac: ENC[AES256_GCM,data:ucn4CjXH3VmoY/+sLzDYCh14SUy11XWTuYbC5ya8GqsaT1ad5rUoKZJaP6Xr+fdBIKrK1m6pH6qnvA4d3Iv9NelLelOi/HN1m38R9ooFwE2mblY23zsDyVNMbG4D7YeuGGkjWCrzArkZqmeUkZd66YGXkRr2+nN9o9Ev7dO6eN4=,iv:E6UnWJZfC18J8F0e/VWWvxDqj/+BGWg4FbfXrKven1s=,tag:HYfTNPm6RCipPqP4l/XIgg==,type:str]
    pgp:
        - created_at: "2024-03-13T20:28:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0B+bz7QWrtpARAA3bclYnLQy7YMP7urNkO+dSOckpwP1v/WMtKAc9UMFx5s
            w4jIyqq0s/4X6qH8OmkOMyvFw+QIDDw3M1Slj2XU/3BsYbo+Coq3J3++IjKOor2t
            gvZqOXe3EAaz+oXVb3HSegrbq0fg2y9+zZSciA1nOPoBerGCYPWVUfNA8l45TIqS
            EXDvzLteXCqAASGaMja5AlZPRKmy6BvFOC7r5mHrmZ2NJ7QW8zX7gWm6qKzL2SGg
            l3DQo8H//weF866dSdorqt1388b9iIIhHjAf2IZ6Ff5M+ykmXBo/kf83AmuB8bhx
            GuJbUvAuO0MJoa74rsiPCpxm/EutbkOWM/lwsKuHHD0mn1NGb3S6Iky4g9VlOapD
            fm9VmYom9DgYBgAQl/PqhkkaICm3IqjPHJPif42qUS+VgNJBsBkuKWu0w9UM9BvG
            WsXOqkMbIsnbnDTOsg99nqYZoxegHlm/LoPd0y386+WcnCntkWcLRXDCyGoIxBuj
            aCDEgsPHiW8fU0tzll46JDIYrstnufutjlQ06hmBN1kOb2SbW9mHBAUqdPBzF92D
            Uj17cQ8pVD33YhaZyCb7im5u5PGmGNfGHabsRbJCkGUs87AyjLg4JlvZa1UQ53Tg
            79+KDCr8gRNE6TXemPeHeEIYM44c78iZemccUMGCFvHEjUMi6wyGnXHn9PahNSLU
            aAEJAhBgA8b3UsoA1OpwFgfLkJtkRVrsj5Za/izElej7zmK0tLjzeYwxFRU0VRZG
            o29h+Sv51ROyK2clKwW5kNJzphmf0HfSRsaReBl27ICdzu3RSf6H8M/Zkv3wr9ZK
            50zYKIkwQIl4
            =su50
            -----END PGP MESSAGE-----
          fp: 89F69D05C9178D00516F584DA2EFD0715D0367AE
    unencrypted_suffix: _unencrypted
    version: 3.8.1
