serviceDns:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.12
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc

ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - pihole.example.com

persistentVolumeClaim:
  enabled: true
